const buildIndexRouteHandler = (sessionInfo) => {
  return async (req, res) => {
    const responseHTML =  buildIndexHtml(sessionInfo);
    res.status(200).set({ 'Content-Type': 'text/html' }).end(responseHTML);
  }
}

const buildIndexHtml = (sessionInfo) => {
  const { domains } = sessionInfo;
  return `
    <!DOCTYPE html>
    <head>
    </head>
		<body>
		  <h1>Hello World!</h1>
		  <p>This markup was generated by the Cloudflare Worker.</p>
      <h1>Domains<h1>
      ${getSiteList(domains)}
		</body>
  `;
}

const getSiteList = (domains) => {
  return '<ul>'
    + domains.reduce((x,y) => x += `<li><a href="http://localhost:3000/proxy?page=http://${y.domain}">${y.domain}</a></li>`, '')
    + '</ul>';
}

module.exports = {
  buildIndexRouteHandler
}
