const buildIndexRouteHandler = (sessionInfo) => {
  return async (req, res) => {
    const responseHTML =  buildIndexHtml(sessionInfo);
    res.status(200).set({ 'Content-Type': 'text/html' }).end(responseHTML);
  }
}

const buildIndexHtml = (sessionInfo) => {
  const { domains } = sessionInfo;
  return `
    <!DOCTYPE html>
    <head>
    </head>
		<body>
		  <h1>Hello World!</h1>
		  <p>This markup was generated by the Cloudflare Worker.</p>
      <p>This will allow us to inject scripts and UI into the resultant preview render after its fetched from the API if we want!</p>
      <p>Here's an example to show the JS embed: <div id="test">0</div></p>
      ${getSiteList(domains)}
      <script>
        ${getEmbeddedJS()}
      </script>
		</body>
  `;
}

const getSiteList = (domains) => {
  return '<ul>'
    + domains.reduce((x,y) => x += `<li><a href="http://localhost:3000/proxy?page=https://www.${y.domain}">${y.domain}</a></li>`, '')
    + '</ul>';
}

const getEmbeddedJS = () => {
  return `
    function nzeros(n){
      var building ='0';
      var i = 0;
      while (i < n-1){
        building+='0';
        i+=1
      }
      return building;
    }
    var z = document.querySelector('#test');
    var goingRight = true;
    function makeStep() {
      if (goingRight) {
        z.innerHTML+='0'
        if (z.innerHTML.length === 10) goingRight=false;
      } else {
        z.innerHTML=nzeros(z.innerHTML.length-1)
        if (z.innerHTML.length === 1) goingRight=true;
      }
    }
    var y = setInterval(makeStep, 100)
  `
}

module.exports = {
  buildIndexRouteHandler
}
